included:
  - Sources
  - Tests
  
excluded:
  - Packages
  - .build
  - .vscode

opt_in_rules:
  - empty_count
  - force_unwrapping
  - file_header

force_cast: warning # implicitly
force_try:
  severity: warning # explicitly

line_length: 100

function_body_length:
  - 50 # warning
  - 100 # error
 
type_body_length:
  - 300 # warning
  - 400 # error

file_length:
  warning: 500
  error: 800

type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 20
    error: 30

identifier_name:
  min_length:
    error: 3
  excluded:
    - id

file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*?\.swift
                    \/\/  (Sanitize|SanitizeTests)
                    \/\/
                    \/\/  Created by .*? on \d{1,2}\/\d{1,2}\/\d{2}\.
                    \/\/  Copyright © \d{4} Gustavo Perdomo\. All rights reserved\.

reporter: "emoji"